[build]
target = "armv7a-none-eabi"
[target.'cfg(all(target_arch = "arm", target_os = "none"))']

rustflags = [
# the GNU linker
#    "-C", "linker=arm-none-eabi-ld"
    "-C", " link-arg=--script=./linker.ld"
]
